name: new_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch
  - cudatoolkit=11.3
  - vtk
  - scikit-image
  - flask
  - flask-cors
  - trimesh
  - numpy
  - open3d
  - pillow
  - pyglet
  - matplotlib
  - scipy
  - tqdm
  - pip:
    - runpod
    - loguru